version: "3.3"
services:
  backend_api:
    container_name: app
    build: ./
    working_dir: /users/project
    command: npm start
    ports:
      - "5000:5000"
    links:
      - mongo
  client:
    container_name: clientapp
    build: ./houses-on-frontend
    working_dir: /users/project/client
    command: npm start
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"